name: gd-godot-engine-snapcraft
license: MIT
summary: Godot Engine
description: |
  Godot Engine
base: core22
grade: stable
confinement: strict
adopt-info: gd-godot-engine-snapcraft
version: 4.1.2-stable

architectures:
  - build-on: amd64
    build-for: amd64

layout:
  /usr/lib/dotnet:
    bind: $SNAP/usr/lib/dotnet
  /usr/share/drirc.d:
    bind: $SNAP/usr/share/drirc.d
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    bind-file: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so:
    bind-file: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    bind-file: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so

apps:
  gd-godot-engine-snapcraft:
    extensions: [gnome]
    command: godot-engine/godot-engine
    environment:
      HOME: $SNAP_USER_COMMON
      VK_ICD_FILENAMESr: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json
    plugs:
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - joystick
      - hardware-observe

parts:
  gd-godot-engine-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      craftctl default
      git checkout "$SNAPCRAFT_PROJECT_VERSION" -b latest
    override-build: |
      # Python
      python3 -c "import sys; print(sys.version)"
      python3 -m pip install scons
      
      # Version
      python3 --version
      pip3 --version
      scons --version
      dotnet --info

      # Scons
      scons platform=linuxbsd target=editor tests=false verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes module_mono_enabled=yes

      # Generate C# glue
      ./bin/godot.* --headless --generate-mono-glue ./modules/mono/glue || true

      # Build .NET Solution
      ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd
      
      # Generate package
      strip bin/godot.*
      chmod +x bin/godot.*
      cd bin
      mv godot.* godot-engine
      mkdir $CRAFT_PART_INSTALL/godot-engine
      mv * $CRAFT_PART_INSTALL/godot-engine
    build-packages:
      - git
      - sed
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libvulkan-dev
      - libglu-dev
      - libasound2-dev
      - libpulse-dev
      - libudev-dev
      - libxi-dev
      - libxrandr-dev
      - python3
      - python3-pip
      - dotnet6
    stage-packages:
      - dotnet6
      - libspeechd2
      - mesa-va-drivers
      - mesa-vulkan-drivers
      - vulkan-tools
      - libegl1-mesa
      - libvulkan1